version: '3'
services:
  nfs:
    build: .
    container_name: nfs-server
    restart: always
    networks:
      - web
    ports:
      - 2049:2049
    volumes:
      - /nfs:/nfs
      - ./conf/exports.txt:/etc/exports:ro
      - /lib/modules:/lib/modules:ro
    cap_add:
      - SYS_ADMIN
      - SYS_MODULE

networks:
  web:
    external: true